added success response
bookaroom/RESTApiExample pull request #25
Opened 2017-04-18 15:42 UTC by rrballenger17

2017-04-18 15:56 UTC, kb000 requested changes

2017-04-18 15:56 UTC, kb000 commented on src/com/comeet/MyResponse.java
> +public class MyResponse implements Serializable {
Please rename to something more descriptive. ComeetBooleanResponse

2017-04-19 04:25 UTC, rrballenger17 commented
Merge

2017-04-19 23:22 UTC, kb000 approved these changes

2017-04-19 23:31 UTC, merged