added get attendees
bookaroom/RESTApiExample pull request #27
Opened 2017-04-19 23:21 UTC by rrballenger17

2017-04-19 23:44 UTC, Dairai commented on src/com/comeet/UserService.java
> +            e.printStackTrace();
You should write the exception to the log using the ApiLogger

2017-04-19 23:45 UTC, kb000 requested changes

2017-04-19 23:45 UTC, kb000 commented on src/com/comeet/Attendees.java
> +    public void setOptionaldattendees(List<Person> people) {
I thought we fixed the contract for this typo "optional *d* attendees"

2017-04-19 23:45 UTC, kb000 commented on src/com/comeet/UsersDao.java
> +        people.setOptionaldattendees(attendees(null, attAppt, opt));
Same typo as above.

2017-04-19 23:45 UTC, kb000 commented on src/com/comeet/UserService.java
> +    @Path("/{orgDomain}/meetings/attendees")
Who requested this route? It's not in the apiary docs.

2017-04-19 23:45 UTC, kb000 commented on src/com/comeet/UserService.java
> +    @Path("/{orgDomain}/meetings/attendees")
Oh I see your comment in slack.

2017-04-19 23:45 UTC, kb000 commented on src/com/comeet/UserService.java
> +                    @DefaultValue("") @FormParam("id") String id)
Meeting needs to expose the id.
Please fork the api builder spec with these changes.
https://github.com/bookaroom/dev-docs/blob/master/apiary.apib

2017-04-20 00:41 UTC, kb000 commented on src/com/comeet/UserService.java
> +                    @DefaultValue("") @FormParam("id") String id)
er... branch... not fork.

2017-04-22 18:36 UTC, Dairai commented on src/com/comeet/UserService.java
> +            e.printStackTrace();
I meant instead of printStackTrace not in addition to. you can change it in another pull request

2017-04-22 19:00 UTC, kb000 approved these changes

2017-04-22 19:00 UTC, merged