Search
bookaroom/RESTApiExample pull request #5
Opened 2017-03-31 07:07 UTC by Dairai

- Implemented search criteria API call
- fixed API logging formatting (need to get a log folder on the servrer)
- fixed the war file name
 
TO-DO
- need to test getBuildingRooms when the token auth is fixed

2017-03-31 15:00 UTC, kb000 requested changes

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/BuildingList.java
> +
Javadoc.

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/RoomsDao.java
> +        } catch (Exception e) {
Please don't swallow Exception. Wrap or re-throw so that errors are reported on the http endpoint.

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/RoomsDao.java
> +     * TODO
I would nag you about this but I'm pretty sure checkstyle in buddy build will😊

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/RoomsDao.java
> +    private List<EmailAddress> getBuildingRoomlist(String email) throws Exception {
Nit: enumerate exception types

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/RoomsDao.java
> +        } catch (Exception ex) {
Don't swallow `Exception`

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/RoomsDao.java
> +        } catch (Exception ex) {
Oh jk. You're not. Remove the TODO.

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/RoomsDao.java
> +            File file = new File("Roo.dat");
I'm not into this caching. Don't we have a DB for that?

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/UserService.java
> +    @Path("/{organization}/searchCriteria")
This route doesn't make sense. It should be an entity noun.

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/UserService.java
> +    //TO-DO: Needs to be tested since there is no
Basic auth works. Send a request with an `Authorization: Basic` header and our test creds.

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/UserService.java
> +            RoomsDao roomsDao = new RoomsDao(null);
You need to build a service and pass it in.

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/data/DataRepository.java
> +            //ApiLogger.logger.log(Level.SEVERE, "Error getting rooms from database database", e);
Why no logging?

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/data/DataRepository.java
> +            //ApiLogger.logger.log(Level.SEVERE, "Error getting rooms from database database", e);
Why no logging?

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/data/DataRepository.java
> +     * Retrieves the search criteria from the database based on the domain
Building lists are search criteria? There's a cognitive mismatch for me here.

2017-03-31 15:00 UTC, kb000 commented on src/com/comeet/data/DataRepository.java
> +                if (searchFields.get(rs.getString(rs.findColumn("Metroarea"))) == null) {
You're auto flattening here? Maybe this should be a separate method.

2017-03-31 17:20 UTC, Dairai commented on src/com/comeet/data/DataRepository.java
> +            //ApiLogger.logger.log(Level.SEVERE, "Error getting rooms from database database", e);
I am trying to have all logging occur in the UserService class. That way we don't log the same exception multiple times as it bubbles up to the top

2017-04-01 02:05 UTC, kb000 commented on src/com/comeet/data/DataRepository.java
> +            //ApiLogger.logger.log(Level.SEVERE, "Error getting rooms from database database", e);
Ok that make sense.  I'm worried that we lose context about just what was going on when the exception was thrown.  I'd rather over log than under log any day.

2017-04-01 02:06 UTC, kb000 commented on src/com/comeet/data/DataRepository.java
> +     * Retrieves the search criteria from the database based on the domain
This is beyond the scope of this change I think.  We should talk about and document our api structure at our next meeting.

2017-04-01 02:07 UTC, kb000 approved these changes
:shipit:

2017-04-01 02:09 UTC, merged